"use client";

import React, { useState, useEffect } from "react";
import AppShell from "@/components/AppShell";
import {
  Sparkles,
  Download,
  Copy,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Info,
  CheckCircle,
} from "lucide-react";

export default function BriefingPage() {
  const [generating, setGenerating] = useState(true);
  const [copied, setCopied] = useState(false);
  const [accordionOpen, setAccordionOpen] = useState(false);

  // Simulate AI briefing generation typing/loading on first mount
  useEffect(() => {
    if (generating) {
      const timer = setTimeout(() => {
        setGenerating(false);
      }, 1500);
      return () => clearTimeout(timer);
    }
  }, [generating]);

  const handleRegenerate = () => {
    setGenerating(true);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(
      "PHC Operations Summary - Today:\n" +
        "1. Critical shortages of ORS Sachets and Albendazole. Expected stockouts in 2.4 days.\n" +
        "2. Evening General OPD shift suffers coverage risk due to the absence of Dr. Ramesh Nair.\n" +
        "3. Pediatrics patient volume surge (+25%) anticipated between 10:00 AM - 1:00 PM."
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    alert("Downloading PDF Report...");
  };

  return (
    <AppShell>
      <div className="briefing-container animate-fade-in">
        {/* Header */}
        <div className="page-header">
          <div className="header-meta">
            <h1 className="page-title">AI Daily Briefing</h1>
            <p className="page-subtitle">Personalized operational recommendations generated by Gemini 2.5 Flash.</p>
          </div>
          <button
            className="btn-secondary flex-center gap-2"
            onClick={handleRegenerate}
            disabled={generating}
          >
            <RefreshCw size={16} className={generating ? "spin-icon" : ""} />
            <span>Regenerate Briefing</span>
          </button>
        </div>

        {generating ? (
          /* Typing / Generating Loader Simulator */
          <div className="generating-card glass-container flex-center flex-col">
            <div className="gemini-badge-pulsing glow-pulsing">
              <svg width="40" height="40" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M90 6C90 19.2548 76.7452 32.51 90 32.51C90 45.765 103.255 32.51 90 32.51C90 19.2548 103.255 6 90 6Z"
                  fill="var(--color-clinical-teal)"
                />
                <path
                  d="M40 30C40 45 30 55 40 55C40 65 50 55 40 55C40 45 50 30 40 30Z"
                  fill="var(--color-primary)"
                />
              </svg>
            </div>
            <h2 className="generating-title">Gemini is synthesizing operations data...</h2>
            <p className="generating-sub">Analyzing stock levels, footfall registers, and shift coverages...</p>
            <div className="generating-progress-bar">
              <div className="progress-fill"></div>
            </div>
          </div>
        ) : (
          /* High Fidelity Synthesized Briefing Page */
          <div className="briefing-grid animate-scale-up">
            {/* Natural language summary card */}
            <section className="summary-card-main glass-container">
              <div className="card-header">
                <div className="header-title-box">
                  <Sparkles size={20} className="text-clinical-teal" />
                  <h2 className="section-title">Today's Synthesis & Action Plan</h2>
                </div>
                <div className="action-button-row">
                  <button className="btn-icon-action" onClick={handleCopy} title="Copy Summary">
                    {copied ? <CheckCircle size={16} className="text-success" /> : <Copy size={16} />}
                    <span>{copied ? "Copied" : "Copy"}</span>
                  </button>
                  <button className="btn-icon-action" onClick={handleDownload} title="Download Report">
                    <Download size={16} />
                    <span>PDF</span>
                  </button>
                </div>
              </div>

              <div className="summary-body">
                <p className="summary-intro text-body-base font-semibold">
                  Good Morning, Doctor. Here is your synthesized operations briefing for Sunday, July 5, 2026.
                </p>

                <div className="summary-section">
                  <h3 className="sub-section-title">📦 Inventory & Supply Chains</h3>
                  <p className="summary-para text-body-sm">
                    We project a stockout of <strong>ORS Sachets</strong> and <strong>Albendazole 400mg</strong> within the next 48 hours. Active usage registers 50 sachets daily, while stock is down to 120. A replenishment request must be approved today to avoid critical shortages by Tuesday.
                  </p>
                </div>

                <div className="summary-section">
                  <h3 className="sub-section-title">👥 Roster & Department Cover</h3>
                  <p className="summary-para text-body-sm">
                    Roster coverage is at <strong>67%</strong> today. Dr. Ramesh Nair is ABSENT for the evening General OPD shift, posing an operational risk. We recommend reallocating Dr. Anita Desai (Gynecology, Afternoon) or inviting Dr. Rajesh Sharma to cover the gap.
                  </p>
                </div>

                <div className="summary-section">
                  <h3 className="sub-section-title">📈 Patient Analytics & Surge Risk</h3>
                  <p className="summary-para text-body-sm">
                    A <strong>25% pediatric patient surge</strong> is predicted between 10:00 AM and 1:00 PM due to seasonal viral patterns. Open an additional registration desk during these hours to prevent OPD queues exceeding 30 minutes.
                  </p>
                </div>
              </div>
            </section>

            {/* Side column: Confidence and Accordion Reasoning */}
            <div className="side-column">
              {/* Confidence Circle Card */}
              <div className="confidence-card glass-container flex-center flex-col">
                <h3 className="side-card-title">Recommendation Confidence</h3>
                <div className="dial-wrapper">
                  <svg className="progress-ring" width="120" height="120">
                    <circle className="progress-ring-bg" stroke="var(--color-surface-container-highest)" strokeWidth="8" fill="transparent" r="50" cx="60" cy="60"/>
                    <circle className="progress-ring-fill" stroke="var(--color-clinical-teal)" strokeDasharray="314.15" strokeDashoffset="18.8" strokeWidth="8" fill="transparent" r="50" cx="60" cy="60"/>
                  </svg>
                  <div className="dial-value">94%</div>
                </div>
                <p className="dial-sub">Confidence score based on historical data match</p>
              </div>

              {/* "Why this recommendation?" reasoning accordion */}
              <div className="accordion-card glass-container">
                <button
                  className="accordion-trigger"
                  onClick={() => setAccordionOpen(!accordionOpen)}
                >
                  <div className="trigger-title-wrapper">
                    <Info size={16} className="text-primary" />
                    <span>Why this recommendation?</span>
                  </div>
                  {accordionOpen ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                </button>

                {accordionOpen && (
                  <div className="accordion-content animate-slide-down">
                    <p className="reasoning-bullet text-body-xs">
                      <strong>Inventory Model:</strong> ORS consumption models are based on the past 14 days of summer diarrheal logs. Stock reorder levels were breached on July 3.
                    </p>
                    <p className="reasoning-bullet text-body-xs">
                      <strong>Surge Model:</strong> The 25% pediatric surge forecast correlates with regional temperature spikes and local school virus reports.
                    </p>
                    <p className="reasoning-bullet text-body-xs">
                      <strong>Roster Model:</strong> Roster reallocations prioritize maintaining minimum pediatric and gynecological specialist coverage thresholds.
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>

      <style jsx global>{`
        .briefing-container {
          padding: var(--spacing-space-6) var(--spacing-space-8);
          max-width: 1200px;
          margin: 0 auto;
        }

        .page-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--spacing-space-6);
        }

        .page-title {
          font-size: 1.75rem;
          font-weight: 700;
          color: var(--color-primary);
          letter-spacing: -0.02em;
        }

        .page-subtitle {
          font-size: 0.875rem;
          color: var(--color-on-surface-variant);
          margin-top: var(--spacing-space-1);
        }

        /* Generating State Loader */
        .generating-card {
          padding: var(--spacing-space-12) var(--spacing-space-6);
          min-height: 400px;
          text-align: center;
        }

        .gemini-badge-pulsing {
          width: 80px;
          height: 80px;
          border-radius: var(--rounded-full);
          background: rgba(13, 148, 136, 0.08);
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: var(--spacing-space-6);
        }

        .generating-title {
          font-size: 1.35rem;
          font-weight: 700;
          color: var(--color-on-surface);
          margin-bottom: var(--spacing-space-2);
        }

        .generating-sub {
          font-size: 0.875rem;
          color: var(--color-outline);
          margin-bottom: var(--spacing-space-6);
        }

        .generating-progress-bar {
          width: 240px;
          height: 6px;
          background-color: var(--color-surface-container-highest);
          border-radius: var(--rounded-full);
          overflow: hidden;
          position: relative;
        }

        .progress-fill {
          height: 100%;
          background: linear-gradient(90deg, var(--color-primary), var(--color-clinical-teal));
          width: 40%;
          border-radius: var(--rounded-full);
          animation: progress-slide 1.5s infinite ease-in-out;
        }

        @keyframes progress-slide {
          0% { left: -40%; width: 40%; }
          50% { width: 60%; }
          100% { left: 100%; width: 40%; }
        }

        .spin-icon {
          animation: spin 1s linear infinite;
        }

        @keyframes spin {
          100% { transform: rotate(360deg); }
        }

        /* Main Briefing Grid */
        .briefing-grid {
          display: grid;
          grid-template-columns: 2fr 1fr;
          gap: var(--spacing-space-6);
          align-items: start;
        }

        .summary-card-main {
          padding: var(--spacing-space-6);
        }

        .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-bottom: 1px solid var(--color-border-subtle);
          padding-bottom: var(--spacing-space-4);
          margin-bottom: var(--spacing-space-4);
        }

        .header-title-box {
          display: flex;
          align-items: center;
          gap: var(--spacing-space-2);
        }

        .action-button-row {
          display: flex;
          gap: var(--spacing-space-2);
        }

        .btn-icon-action {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 6px 12px;
          background: var(--color-surface-container);
          border: 1px solid var(--color-border-subtle);
          border-radius: var(--rounded-md);
          font-size: 0.75rem;
          font-weight: 600;
          cursor: pointer;
          color: var(--color-on-surface-variant);
          transition: all 0.2s;
        }

        .btn-icon-action:hover {
          background: var(--color-surface-container-highest);
          color: var(--color-primary);
        }

        .summary-intro {
          margin-bottom: var(--spacing-space-6);
          color: var(--color-on-surface);
        }

        .summary-section {
          margin-bottom: var(--spacing-space-5);
        }

        .sub-section-title {
          font-size: 0.875rem;
          font-weight: 700;
          color: var(--color-primary);
          margin-bottom: var(--spacing-space-2);
          text-transform: uppercase;
          letter-spacing: 0.03em;
        }

        .summary-para {
          line-height: 1.6;
          color: var(--color-on-surface-variant);
        }

        /* Side Column */
        .side-column {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-space-6);
        }

        .confidence-card {
          padding: var(--spacing-space-6);
          text-align: center;
        }

        .side-card-title {
          font-size: 0.875rem;
          font-weight: 700;
          color: var(--color-on-surface);
          margin-bottom: var(--spacing-space-4);
        }

        .dial-wrapper {
          position: relative;
          width: 120px;
          height: 120px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: var(--spacing-space-3);
        }

        .progress-ring {
          transform: rotate(-90deg);
        }

        .progress-ring-fill {
          transition: stroke-dashoffset 0.35s;
          transform-origin: 50% 50%;
        }

        .dial-value {
          position: absolute;
          font-size: 1.5rem;
          font-weight: 700;
          color: var(--color-clinical-teal);
        }

        .dial-sub {
          font-size: 0.75rem;
          color: var(--color-outline);
          line-height: 1.4;
          padding: 0 var(--spacing-space-2);
        }

        /* Accordion Card */
        .accordion-card {
          padding: var(--spacing-space-4);
        }

        .accordion-trigger {
          width: 100%;
          background: none;
          border: none;
          display: flex;
          justify-content: space-between;
          align-items: center;
          cursor: pointer;
          padding: 4px 0;
          color: var(--color-on-surface);
          font-weight: 700;
          font-size: 0.875rem;
        }

        .trigger-title-wrapper {
          display: flex;
          align-items: center;
          gap: var(--spacing-space-2);
        }

        .accordion-content {
          margin-top: var(--spacing-space-3);
          border-top: 1px solid var(--color-border-subtle);
          padding-top: var(--spacing-space-3);
          display: flex;
          flex-direction: column;
          gap: var(--spacing-space-3);
        }

        .reasoning-bullet {
          line-height: 1.4;
          color: var(--color-on-surface-variant);
        }

        @media (max-width: 768px) {
          .briefing-grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </AppShell>
  );
}
