"use client";

import React, { useState, useEffect } from "react";
import AppShell from "@/components/AppShell";
import { useBriefing } from "@/hooks/useBriefing";
import {
  Sparkles,
  Download,
  Copy,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Info,
  CheckCircle,
} from "lucide-react";

export default function BriefingPage() {
  const { briefing, confidence, reasoning, fallbackActive, loading, isGenerating, generateBriefing } = useBriefing();
  const [copied, setCopied] = useState(false);
  const [accordionOpen, setAccordionOpen] = useState(false);

  // Helper to parse sections from briefing text dynamically
  const parseBriefing = (text: string | null) => {
    if (!text) return { intro: "", inventory: "", roster: "", surge: "" };
    const lines = text.split("\n\n");
    const intro = lines[0] || "";
    let inventory = "";
    let roster = "";
    let surge = "";

    lines.forEach((chunk) => {
      if (chunk.includes("Inventory")) {
        inventory = chunk.replace(/.*Inventory.*\n/, "");
      } else if (chunk.includes("Roster")) {
        roster = chunk.replace(/.*Roster.*\n/, "");
      } else if (chunk.includes("Patient")) {
        surge = chunk.replace(/.*Patient.*\n/, "");
      }
    });

    return { intro, inventory, roster, surge };
  };

  const { intro, inventory, roster, surge } = parseBriefing(briefing);

  const handleCopy = () => {
    if (briefing) {
      navigator.clipboard.writeText(briefing);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    alert("Downloading PDF Report...");
  };

  const generating = loading || isGenerating;

  return (
    <AppShell>
      <div className="briefing-container animate-fade-in">
        {/* Header */}
        <div className="page-header" style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '8px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center' }}>
            <div className="header-meta">
              <h1 className="page-title">AI Daily Briefing</h1>
              <p className="page-subtitle">Personalized operational recommendations generated by Gemini 2.5 Flash.</p>
            </div>
            <button
              className="btn-secondary flex-center gap-2"
              onClick={generateBriefing}
              disabled={generating}
            >
              <RefreshCw size={16} className={generating ? "spin-icon" : ""} />
              <span>Regenerate Briefing</span>
            </button>
          </div>
          {fallbackActive && (
            <div className="fallback-warning-badge flex-center gap-1 text-warning font-semibold text-body-xs" style={{ display: 'inline-flex', background: 'rgba(217, 119, 6, 0.1)', border: '1px solid rgba(217, 119, 6, 0.3)', padding: '6px 12px', borderRadius: '6px', color: 'var(--color-warning)' }}>
              <AlertTriangle size={14} />
              <span>Live Gemini API offline. Displaying local simulated briefing data.</span>
            </div>
          )}
        </div>

        {generating ? (
          /* Typing / Generating Loader Simulator */
          <div className="generating-card glass-container flex-center flex-col">
            <div className="gemini-badge-pulsing glow-pulsing">
              <svg width="40" height="40" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M90 6C90 19.2548 76.7452 32.51 90 32.51C90 45.765 103.255 32.51 90 32.51C90 19.2548 103.255 6 90 6Z"
                  fill="var(--color-clinical-teal)"
                />
                <path
                  d="M40 30C40 45 30 55 40 55C40 65 50 55 40 55C40 45 50 30 40 30Z"
                  fill="var(--color-primary)"
                />
              </svg>
            </div>
            <h2 className="generating-title">Gemini is synthesizing operations data...</h2>
            <p className="generating-sub">Analyzing stock levels, footfall registers, and shift coverages...</p>
            <div className="generating-progress-bar">
              <div className="progress-fill"></div>
            </div>
          </div>
        ) : (
          /* High Fidelity Synthesized Briefing Page */
          <div className="briefing-grid animate-scale-up">
            {/* Natural language summary card */}
            <section className="summary-card-main glass-container">
              <div className="card-header">
                <div className="header-title-box">
                  <Sparkles size={20} className="text-clinical-teal" />
                  <h2 className="section-title">Today&apos;s Synthesis & Action Plan</h2>
                </div>
                <div className="action-button-row">
                  <button className="btn-icon-action" onClick={handleCopy} title="Copy Summary">
                    {copied ? <CheckCircle size={16} className="text-success" /> : <Copy size={16} />}
                    <span>{copied ? "Copied" : "Copy"}</span>
                  </button>
                  <button className="btn-icon-action" onClick={handleDownload} title="Download Report">
                    <Download size={16} />
                    <span>PDF</span>
                  </button>
                </div>
              </div>

              <div className="summary-body">
                <p className="summary-intro text-body-base font-semibold">
                  {intro}
                </p>

                {inventory && (
                  <div className="summary-section">
                    <h3 className="sub-section-title">📦 Inventory & Supply Chains</h3>
                    <p className="summary-para text-body-sm">
                      {inventory}
                    </p>
                  </div>
                )}

                {roster && (
                  <div className="summary-section">
                    <h3 className="sub-section-title">👥 Roster & Department Cover</h3>
                    <p className="summary-para text-body-sm">
                      {roster}
                    </p>
                  </div>
                )}

                {surge && (
                  <div className="summary-section">
                    <h3 className="sub-section-title">📈 Patient Analytics & Surge Risk</h3>
                    <p className="summary-para text-body-sm">
                      {surge}
                    </p>
                  </div>
                )}
              </div>
            </section>

            {/* Side column: Accordion Reasoning */}
            <div className="side-column">
              {/* "Why this recommendation?" reasoning accordion */}
              <div className="accordion-card glass-container">
                <button
                  className="accordion-trigger"
                  onClick={() => setAccordionOpen(!accordionOpen)}
                >
                  <div className="trigger-title-wrapper">
                    <Info size={16} className="text-primary" />
                    <span>Why this recommendation?</span>
                  </div>
                  {accordionOpen ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                </button>

                {accordionOpen && (
                  <div className="accordion-content animate-slide-down">
                    <p className="reasoning-bullet text-body-xs">
                      <strong>Inventory Model:</strong> {reasoning.inventory}
                    </p>
                    <p className="reasoning-bullet text-body-xs">
                      <strong>Surge Model:</strong> {reasoning.surge}
                    </p>
                    <p className="reasoning-bullet text-body-xs">
                      <strong>Roster Model:</strong> {reasoning.roster}
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}
      </div>

      <style jsx global>{`
        .briefing-container {
          padding: var(--spacing-space-6) var(--spacing-space-8);
          max-width: 1200px;
          margin: 0 auto;
        }

        .page-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--spacing-space-6);
        }

        .page-title {
          font-size: 1.75rem;
          font-weight: 700;
          color: var(--color-primary);
          letter-spacing: -0.02em;
        }

        .page-subtitle {
          font-size: 0.875rem;
          color: var(--color-on-surface-variant);
          margin-top: var(--spacing-space-1);
        }

        /* Generating State Loader */
        .generating-card {
          padding: var(--spacing-space-12) var(--spacing-space-6);
          min-height: 400px;
          text-align: center;
        }

        .gemini-badge-pulsing {
          width: 80px;
          height: 80px;
          border-radius: var(--rounded-full);
          background: rgba(13, 148, 136, 0.08);
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: var(--spacing-space-6);
        }

        .generating-title {
          font-size: 1.35rem;
          font-weight: 700;
          color: var(--color-on-surface);
          margin-bottom: var(--spacing-space-2);
        }

        .generating-sub {
          font-size: 0.875rem;
          color: var(--color-outline);
          margin-bottom: var(--spacing-space-6);
        }

        .generating-progress-bar {
          width: 240px;
          height: 6px;
          background-color: var(--color-surface-container-highest);
          border-radius: var(--rounded-full);
          overflow: hidden;
          position: relative;
        }

        .progress-fill {
          height: 100%;
          background: linear-gradient(90deg, var(--color-primary), var(--color-clinical-teal));
          width: 40%;
          border-radius: var(--rounded-full);
          animation: progress-slide 1.5s infinite ease-in-out;
        }

        @keyframes progress-slide {
          0% { left: -40%; width: 40%; }
          50% { width: 60%; }
          100% { left: 100%; width: 40%; }
        }

        .spin-icon {
          animation: spin 1s linear infinite;
        }

        @keyframes spin {
          100% { transform: rotate(360deg); }
        }

        /* Main Briefing Grid */
        .briefing-grid {
          display: grid;
          grid-template-columns: 2fr 1fr;
          gap: var(--spacing-space-6);
          align-items: start;
        }

        .summary-card-main {
          padding: var(--spacing-space-6);
        }

        .card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          border-bottom: 1px solid var(--color-border-subtle);
          padding-bottom: var(--spacing-space-4);
          margin-bottom: var(--spacing-space-4);
        }

        .header-title-box {
          display: flex;
          align-items: center;
          gap: var(--spacing-space-2);
        }

        .action-button-row {
          display: flex;
          gap: var(--spacing-space-2);
        }

        .btn-icon-action {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 6px 12px;
          background: var(--color-surface-container);
          border: 1px solid var(--color-border-subtle);
          border-radius: var(--rounded-md);
          font-size: 0.75rem;
          font-weight: 600;
          cursor: pointer;
          color: var(--color-on-surface-variant);
          transition: all 0.2s;
        }

        .btn-icon-action:hover {
          background: var(--color-surface-container-highest);
          color: var(--color-primary);
        }

        .summary-intro {
          margin-bottom: var(--spacing-space-6);
          color: var(--color-on-surface);
        }

        .summary-section {
          margin-bottom: var(--spacing-space-5);
        }

        .sub-section-title {
          font-size: 0.875rem;
          font-weight: 700;
          color: var(--color-primary);
          margin-bottom: var(--spacing-space-2);
          text-transform: uppercase;
          letter-spacing: 0.03em;
        }

        .summary-para {
          line-height: 1.6;
          color: var(--color-on-surface-variant);
        }

        /* Side Column */
        .side-column {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-space-6);
        }

        .confidence-card {
          padding: var(--spacing-space-6);
          text-align: center;
        }

        .side-card-title {
          font-size: 0.875rem;
          font-weight: 700;
          color: var(--color-on-surface);
          margin-bottom: var(--spacing-space-4);
        }

        .dial-wrapper {
          position: relative;
          width: 120px;
          height: 120px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: var(--spacing-space-3);
        }

        .progress-ring {
          transform: rotate(-90deg);
        }

        .progress-ring-fill {
          transition: stroke-dashoffset 0.35s;
          transform-origin: 50% 50%;
        }

        .dial-value {
          position: absolute;
          font-size: 1.5rem;
          font-weight: 700;
          color: var(--color-clinical-teal);
        }

        .dial-sub {
          font-size: 0.75rem;
          color: var(--color-outline);
          line-height: 1.4;
          padding: 0 var(--spacing-space-2);
        }

        /* Accordion Card */
        .accordion-card {
          padding: var(--spacing-space-4);
        }

        .accordion-trigger {
          width: 100%;
          background: none;
          border: none;
          display: flex;
          justify-content: space-between;
          align-items: center;
          cursor: pointer;
          padding: 4px 0;
          color: var(--color-on-surface);
          font-weight: 700;
          font-size: 0.875rem;
        }

        .trigger-title-wrapper {
          display: flex;
          align-items: center;
          gap: var(--spacing-space-2);
        }

        .accordion-content {
          margin-top: var(--spacing-space-3);
          border-top: 1px solid var(--color-border-subtle);
          padding-top: var(--spacing-space-3);
          display: flex;
          flex-direction: column;
          gap: var(--spacing-space-3);
        }

        .reasoning-bullet {
          line-height: 1.4;
          color: var(--color-on-surface-variant);
        }

        @media (max-width: 768px) {
          .briefing-grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </AppShell>
  );
}
