"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";

export default function OnboardingSlides() {
  const [currentSlide, setCurrentSlide] = useState(0);
  const router = useRouter();

  const slides = [
    {
      title: "Smarter PHC Operations",
      description:
        "Manage medicines, patient flow, and doctor availability from one intelligent command center dashboard.",
      illustration: (
        <svg viewBox="0 0 200 150" className="onboarding-svg">
          {/* Dashboard shell */}
          <rect x="20" y="20" width="160" height="110" rx="8" fill="#1e293b" opacity="0.9" />
          <rect x="28" y="28" width="40" height="40" rx="4" fill="#334155" />
          <rect x="74" y="28" width="98" height="40" rx="4" fill="#334155" />
          <rect x="28" y="74" width="70" height="48" rx="4" fill="#334155" />
          <rect x="104" y="74" width="68" height="48" rx="4" fill="#334155" />
          
          {/* Charts/Stats mock inside */}
          <circle cx="48" cy="48" r="14" fill="none" stroke="var(--color-clinical-teal)" strokeWidth="4" />
          <path d="M74 48h98" stroke="rgba(255,255,255,0.2)" strokeWidth="4" />
          <rect x="114" y="86" width="48" height="18" rx="2" fill="var(--color-secondary)" />
          <path d="M40 96 l16-16 12 12 20-20" fill="none" stroke="#f59e0b" strokeWidth="3" />
        </svg>
      ),
    },
    {
      title: "AI That Helps You Decide",
      description:
        "Get intelligent operational recommendations generated by Google Gemini instead of manually analyzing spreadsheet reports.",
      illustration: (
        <svg viewBox="0 0 200 150" className="onboarding-svg">
          {/* Brain / Sparkles AI system */}
          <circle cx="100" cy="75" r="30" fill="none" stroke="var(--color-clinical-teal)" strokeWidth="3" />
          <circle cx="100" cy="75" r="45" fill="none" stroke="rgba(13, 148, 136, 0.2)" strokeWidth="2" strokeDasharray="4 4" />
          
          {/* Nodes */}
          <circle cx="100" cy="45" r="6" fill="var(--color-secondary)" />
          <circle cx="70" cy="75" r="6" fill="#10b981" />
          <circle cx="130" cy="75" r="6" fill="#ef4444" />
          <circle cx="100" cy="105" r="6" fill="#f59e0b" />
          
          {/* AI Spark in center */}
          <path
            d="M100 62c0 6.5-5.5 13-13 13c7.5 0 13 6.5 13 13c0-6.5 5.5-13 13-13c-7.5 0-13-6.5-13-13z"
            fill="var(--color-clinical-teal)"
          />
          
          {/* Connection lines */}
          <line x1="100" y1="51" x2="100" y2="62" stroke="var(--color-border-subtle)" strokeWidth="2" />
          <line x1="76" y1="75" x2="87" y2="75" stroke="var(--color-border-subtle)" strokeWidth="2" />
          <line x1="124" y1="75" x2="113" y2="75" stroke="var(--color-border-subtle)" strokeWidth="2" />
          <line x1="100" y1="99" x2="100" y2="88" stroke="var(--color-border-subtle)" strokeWidth="2" />
        </svg>
      ),
    },
    {
      title: "Stay One Step Ahead",
      description:
        "Predict medicine shortages, patient footfall surges, and coverage gaps before they happen so you can allocate staff proactively.",
      illustration: (
        <svg viewBox="0 0 200 150" className="onboarding-svg">
          {/* Surge alert and shield/checkmark */}
          <rect x="30" y="30" width="140" height="90" rx="8" fill="#f8fafc" stroke="var(--color-border-subtle)" strokeWidth="2" />
          
          {/* Alert symbol */}
          <path d="M100 45 L118 78 H82 Z" fill="#f59e0b" />
          <text x="100" y="74" fill="#ffffff" fontSize="12" fontWeight="bold" textAnchor="middle">!</text>
          
          {/* Dynamic indicators */}
          <rect x="50" y="90" width="100" height="8" rx="4" fill="var(--color-surface-container)" />
          <rect x="50" y="90" width="78" height="8" rx="4" fill="var(--color-clinical-teal)" />
          
          {/* Pulse circles */}
          <circle cx="100" cy="62" r="28" fill="none" stroke="rgba(245, 158, 11, 0.15)" strokeWidth="2" className="pulse-ring" />
        </svg>
      ),
    },
  ];

  const handleNext = () => {
    if (currentSlide < slides.length - 1) {
      setCurrentSlide(currentSlide + 1);
    } else {
      handleComplete();
    }
  };

  const handleSkip = () => {
    handleComplete();
  };

  const handleComplete = () => {
    localStorage.setItem("phc_first_visit_complete", "true");
    router.push("/dashboard");
  };

  return (
    <div className="onboarding-container animate-fade-in">
      <div className="onboarding-card glass-container">
        
        {/* Skip button on top right */}
        {currentSlide < slides.length - 1 && (
          <button className="skip-button" onClick={handleSkip}>
            Skip
          </button>
        )}

        {/* Slide contents */}
        <div className="illustration-wrapper">
          {slides[currentSlide].illustration}
        </div>

        <div className="content-wrapper">
          <h2 className="slide-title">{slides[currentSlide].title}</h2>
          <p className="slide-desc">{slides[currentSlide].description}</p>
        </div>

        {/* Footer controls */}
        <div className="controls-wrapper">
          {/* Dots */}
          <div className="dots-indicator">
            {slides.map((_, index) => (
              <span
                key={index}
                className={`dot ${index === currentSlide ? "dot-active" : ""}`}
                onClick={() => setCurrentSlide(index)}
              />
            ))}
          </div>

          {/* Action button */}
          <button className="primary-action-button" onClick={handleNext}>
            {currentSlide === slides.length - 1 ? "Get Started" : "Next"}
          </button>
        </div>

      </div>

      <style jsx>{`
        .onboarding-container {
          min-height: 100vh;
          width: 100vw;
          display: flex;
          align-items: center;
          justify-content: center;
          background: radial-gradient(circle at 50% 50%, #ffffff 0%, var(--color-background) 100%);
          padding: var(--spacing-margin-page);
        }

        .onboarding-card {
          width: 100%;
          max-width: 440px;
          padding: var(--spacing-space-8) var(--spacing-space-6) var(--spacing-space-6);
          position: relative;
          display: flex;
          flex-direction: column;
          align-items: center;
          text-align: center;
          min-height: 480px;
        }

        .skip-button {
          position: absolute;
          top: var(--spacing-space-4);
          right: var(--spacing-space-4);
          font-size: 0.875rem;
          font-weight: 600;
          color: var(--color-on-surface-variant);
          padding: var(--spacing-space-1) var(--spacing-space-2);
          border-radius: var(--rounded-sm);
        }
        
        .skip-button:hover {
          background-color: var(--color-surface-container);
        }

        .illustration-wrapper {
          height: 180px;
          width: 100%;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: var(--spacing-space-6);
        }

        .onboarding-svg {
          width: 100%;
          max-width: 240px;
          height: auto;
        }

        .content-wrapper {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          margin-bottom: var(--spacing-space-6);
        }

        .slide-title {
          font-size: 1.5rem;
          font-weight: 700;
          color: var(--color-primary);
          margin-bottom: var(--spacing-space-2);
          letter-spacing: -0.015em;
        }

        .slide-desc {
          font-size: 0.95rem;
          line-height: 1.5;
          color: var(--color-on-surface-variant);
        }

        .controls-wrapper {
          width: 100%;
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-top: auto;
          border-top: 1px solid var(--color-border-subtle);
          padding-top: var(--spacing-space-4);
        }

        .dots-indicator {
          display: flex;
          gap: var(--spacing-space-2);
        }

        .dot {
          width: 8px;
          height: 8px;
          border-radius: var(--rounded-full);
          background-color: var(--color-outline-variant);
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .dot-active {
          background-color: var(--color-clinical-teal);
          width: 20px;
        }

        .primary-action-button {
          background-color: var(--color-primary);
          color: var(--color-on-primary);
          font-size: 0.875rem;
          font-weight: 600;
          padding: var(--spacing-space-2) var(--spacing-space-6);
          border-radius: var(--rounded-default);
          box-shadow: 0 4px 10px rgba(9, 20, 38, 0.15);
        }

        .primary-action-button:hover {
          background-color: var(--color-primary-container);
          transform: translateY(-1px);
        }

        @keyframes pulseRing {
          0% { transform: scale(0.95); opacity: 0.5; }
          50% { transform: scale(1.05); opacity: 1; }
          100% { transform: scale(0.95); opacity: 0.5; }
        }

        .pulse-ring {
          transform-origin: center;
          animation: pulseRing 3s infinite ease-in-out;
        }
      `}</style>
    </div>
  );
}
